name: flutter_locales
description: Easily localize your app to multiple languages
version: 0.0.4
homepage: https:popal.dev
repository: https://github.com/iampopal/flutter_locales
documentation: https://github.com/iampopal/flutter_locales
issue_tracker: https://github.com/iampopal/flutter_locales/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^0.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
