name: flutter_locales
description: A new Flutter package project.
version: 0.0.2
homepage: https://popal.dev

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^0.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
